name: Knockdown
version: '${project.version}'
main: jp.houlab.mochidsuki.knockdown.Main
api-version: '1.20'

depend:
  - ProtocolLib

softdepend:
  - BattleInventory
  - ArmorShield

commands:
  watchscore:
    aliases: [wscore]
    description: 戦績確認コマンド
    permission: knockdown.command.watchscore
    permission-message: Permission denied
    usage: gr reload